// Package swagger Code generated by swaggo/swag. DO NOT EDIT
package swagger

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "time-trial contributors"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/param-resp": {
            "post": {
                "description": "Configures the schema used to generate response bodies when a 200 is returned by /sabotage or /plan/sabotage. Only statusCode=200 is supported. With no body, clears the active configuration (returns {active:false}).",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "param-resp"
                ],
                "summary": "Set param-resp configuration",
                "parameters": [
                    {
                        "description": "Response schema configuration. Omit body to clear.",
                        "name": "body",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/entities.ResponseConfig"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.EnvelopeSetParamResp"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handlers.EnvelopeError"
                        }
                    }
                }
            }
        },
        "/param-resp/config": {
            "get": {
                "description": "Returns the active response-body schema exactly as submitted. Returns 404 if no configuration is active.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "param-resp"
                ],
                "summary": "Get param-resp configuration",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.EnvelopeParamRespConfig"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/handlers.EnvelopeError"
                        }
                    }
                }
            }
        },
        "/plan": {
            "post": {
                "description": "Loads an ordered list of sabotage steps. Steps are consumed in order on GET /plan/sabotage. With no body, clears the active plan (returns {active:false}).",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "plan"
                ],
                "summary": "Set or clear plan",
                "parameters": [
                    {
                        "description": "Ordered plan. Omit body to clear.",
                        "name": "body",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/handlers.planRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.EnvelopeSetPlan"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handlers.EnvelopeError"
                        }
                    }
                }
            }
        },
        "/plan/config": {
            "get": {
                "description": "Returns all steps of the active plan regardless of how many have been consumed. Returns 404 if no plan is loaded.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "plan"
                ],
                "summary": "Get plan configuration",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.EnvelopePlanConfig"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/handlers.EnvelopeError"
                        }
                    }
                }
            }
        },
        "/plan/sabotage": {
            "get": {
                "description": "Consumes the next step from the active plan. Returns 404 if no plan is loaded, all steps are consumed, or the plan was interrupted.\nWhen step code=200 and a param-resp config is active, \"data\" is dynamically generated — its schema depends on the active configuration. See GET /param-resp/config.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "exec"
                ],
                "summary": "Execute next plan step",
                "responses": {
                    "200": {
                        "description": "data is either SabotageStateResponse or dynamically generated (see GET /param-resp/config)",
                        "schema": {
                            "$ref": "#/definitions/handlers.EnvelopeDynamic"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handlers.EnvelopeSabotageState"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/handlers.EnvelopeError"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handlers.EnvelopeSabotageState"
                        }
                    }
                }
            }
        },
        "/sabotage": {
            "get": {
                "description": "Responds with the configured HTTP code (or random 200/400/500 when code=0). Applies delay if configured.\nWhen code=200 and a param-resp config is active, \"data\" is dynamically generated — its schema depends on the active configuration. See GET /param-resp/config.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "exec"
                ],
                "summary": "Execute sabotage",
                "responses": {
                    "200": {
                        "description": "data is either SabotageStateResponse or dynamically generated (see GET /param-resp/config)",
                        "schema": {
                            "$ref": "#/definitions/handlers.EnvelopeDynamic"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handlers.EnvelopeSabotageState"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/handlers.EnvelopeSabotageState"
                        }
                    }
                }
            }
        },
        "/time-trial": {
            "post": {
                "description": "Sets the active forced status code and optional delay range. With no body, resets to random behavior (code=0, delays=0).",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "sabotage"
                ],
                "summary": "Set sabotage configuration",
                "parameters": [
                    {
                        "description": "Sabotage configuration. Omit body to reset.",
                        "name": "body",
                        "in": "body",
                        "schema": {
                            "$ref": "#/definitions/handlers.sabotageRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.EnvelopeSetSabotage"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/handlers.EnvelopeError"
                        }
                    }
                }
            }
        },
        "/time-trial/config": {
            "get": {
                "description": "Returns the active forced status code and delay range. code=0 means random behavior.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "sabotage"
                ],
                "summary": "Get sabotage configuration",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/handlers.EnvelopeSabotageConfig"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "entities.ItemConfig": {
            "type": "object",
            "properties": {
                "isColection": {
                    "type": "boolean"
                },
                "properties": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/entities.Property"
                    }
                },
                "quantity": {
                    "type": "integer"
                }
            }
        },
        "entities.Property": {
            "type": "object",
            "properties": {
                "isRequired": {
                    "type": "boolean"
                },
                "maxLength": {
                    "type": "integer"
                },
                "minLength": {
                    "type": "integer"
                },
                "name": {
                    "type": "string"
                },
                "propertyFloat": {
                    "$ref": "#/definitions/entities.PropertyFloatConfig"
                },
                "propertyInt": {
                    "$ref": "#/definitions/entities.PropertyIntConfig"
                },
                "propertyString": {
                    "$ref": "#/definitions/entities.PropertyStringConfig"
                },
                "type": {
                    "$ref": "#/definitions/entities.PropertyType"
                }
            }
        },
        "entities.PropertyFloatConfig": {
            "type": "object",
            "properties": {
                "floatPrecision": {
                    "type": "integer"
                },
                "isAcceptNegativeValue": {
                    "type": "boolean"
                }
            }
        },
        "entities.PropertyIntConfig": {
            "type": "object",
            "properties": {
                "isAcceptNegativeValue": {
                    "type": "boolean"
                }
            }
        },
        "entities.PropertyStringConfig": {
            "type": "object",
            "properties": {
                "chars": {
                    "type": "string"
                }
            }
        },
        "entities.PropertyType": {
            "type": "string",
            "enum": [
                "string",
                "int",
                "float"
            ],
            "x-enum-varnames": [
                "PropertyTypeString",
                "PropertyTypeInt",
                "PropertyTypeFloat"
            ]
        },
        "entities.ResponseConfig": {
            "type": "object",
            "properties": {
                "item": {
                    "$ref": "#/definitions/entities.ItemConfig"
                },
                "statusCode": {
                    "type": "integer"
                }
            }
        },
        "handlers.EnvelopeDynamic": {
            "type": "object",
            "properties": {
                "data": {},
                "duration": {
                    "type": "integer"
                },
                "timestamp": {
                    "type": "string"
                }
            }
        },
        "handlers.EnvelopeError": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/handlers.ErrorResponse"
                },
                "duration": {
                    "type": "integer"
                },
                "timestamp": {
                    "type": "string"
                }
            }
        },
        "handlers.EnvelopeParamRespConfig": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/entities.ResponseConfig"
                },
                "duration": {
                    "type": "integer"
                },
                "timestamp": {
                    "type": "string"
                }
            }
        },
        "handlers.EnvelopePlanConfig": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/handlers.PlanConfigResponse"
                },
                "duration": {
                    "type": "integer"
                },
                "timestamp": {
                    "type": "string"
                }
            }
        },
        "handlers.EnvelopeSabotageConfig": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/handlers.SabotageConfigResponse"
                },
                "duration": {
                    "type": "integer"
                },
                "timestamp": {
                    "type": "string"
                }
            }
        },
        "handlers.EnvelopeSabotageState": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/handlers.SabotageStateResponse"
                },
                "duration": {
                    "type": "integer"
                },
                "timestamp": {
                    "type": "string"
                }
            }
        },
        "handlers.EnvelopeSetParamResp": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/handlers.SetParamRespResponse"
                },
                "duration": {
                    "type": "integer"
                },
                "timestamp": {
                    "type": "string"
                }
            }
        },
        "handlers.EnvelopeSetPlan": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/handlers.SetPlanResponse"
                },
                "duration": {
                    "type": "integer"
                },
                "timestamp": {
                    "type": "string"
                }
            }
        },
        "handlers.EnvelopeSetSabotage": {
            "type": "object",
            "properties": {
                "data": {
                    "$ref": "#/definitions/handlers.SetSabotageResponse"
                },
                "duration": {
                    "type": "integer"
                },
                "timestamp": {
                    "type": "string"
                }
            }
        },
        "handlers.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                }
            }
        },
        "handlers.PlanConfigResponse": {
            "type": "object",
            "properties": {
                "active": {
                    "type": "boolean"
                },
                "steps": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/handlers.PlanStepConfig"
                    }
                }
            }
        },
        "handlers.PlanStepConfig": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "delayMax": {
                    "type": "integer"
                },
                "delayMin": {
                    "type": "integer"
                }
            }
        },
        "handlers.SabotageConfigResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "delayMax": {
                    "type": "integer"
                },
                "delayMin": {
                    "type": "integer"
                },
                "sabotaged": {
                    "type": "boolean"
                }
            }
        },
        "handlers.SabotageStateResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "sabotaged": {
                    "type": "boolean"
                }
            }
        },
        "handlers.SetParamRespResponse": {
            "type": "object",
            "properties": {
                "active": {
                    "type": "boolean"
                },
                "properties": {
                    "type": "integer"
                },
                "statusCode": {
                    "type": "integer"
                }
            }
        },
        "handlers.SetPlanResponse": {
            "type": "object",
            "properties": {
                "active": {
                    "type": "boolean"
                },
                "steps": {
                    "type": "integer"
                }
            }
        },
        "handlers.SetSabotageResponse": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "delayMax": {
                    "type": "integer"
                },
                "delayMin": {
                    "type": "integer"
                },
                "sabotaged": {
                    "type": "boolean"
                }
            }
        },
        "handlers.planRequest": {
            "type": "object",
            "properties": {
                "plan": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/handlers.planStepRequest"
                    }
                }
            }
        },
        "handlers.planStepRequest": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "delayMax": {
                    "type": "integer"
                },
                "delayMin": {
                    "type": "integer"
                }
            }
        },
        "handlers.sabotageRequest": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "integer"
                },
                "delayMax": {
                    "type": "integer"
                },
                "delayMin": {
                    "type": "integer"
                }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:7777",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "time-trial API",
	Description:      "Minimal service for injecting controlled HTTP failures (status codes, delays, dynamic response bodies) into dependent services during testing.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
